from flask_assets import Bundle

bundles = {
    'main_scss':Bundle(
        'scss/main.scss',
        filters='libsass',
        depends=[
            'scss/*.scss',
            'scss/base/*.scss',
            'scss/pages/*.scss',
            'scss/components/navbars/*.scss',
            'scss/components/pieces/*.scss',
            'scss/components/sections/*.scss',
        ],
        output='gen/css/main.%(version)s.css'
    ),
    'base_js':Bundle(
        'js/base/contact_modal.js',
        'js/base/dramatic_h1.js',
        'js/base/hidden.js',
        filters='jsmin',
        depends=[
            'js/three_d/*.js',
        ],
        output='gen/js/base.%(version)s.js'
    ),
    'index_js':Bundle(
        'js/index/experience.js',
        'js/index/hero.js',
        'js/index/planets_mod.js',
        'js/index/resume_like.js',
        'js/index/shifting_dots.js',
        'js/index/skill_card.js',
        'js/index/story.js',
        filters='jsmin',
        depends=[
            'js/animations/*.js',
        ],
        output='gen/js/index.%(version)s.js'
    ),
    'styles':Bundle(
        'js/animations/glassmin.js',
        'js/animations/minimalism.js',
        'js/animations/neubrutalism.js',
        filters='jsmin',
        depends=[
            'js/three_d/*.js',
        ],
        output='gen/js/styles.%(version)s.js'
    ),
}

