name: Build and Deploy Code

on:
    push:
      branches: ["production"]

jobs:
  job1:
    runs-on: ububtu-latest
    steps:
      - name: pull git repo
        uses: actions/checkout@v2
      - name: say hi to me
        run: echo 'hi alex'