name: Build and Deploy Code

on:
    push:
      branches: ["main"]

jobs:
  build:
    environment:
      name: portfolio


    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: set up python v3
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: installing all dependencies
        run: pip install -r requirements/requirements.txt
      - name: run pytest
        run: |
          pip install pytest
          pytest -v -s
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: production
    steps:
      - name: deploy to ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: www.barreradev.com
          username: ${{secrets.PROD_USERNAME}}
          password: ${{secrets.PROD_PASSWORD}}


          # script: |
          #   cd portfolio
          #   git pull
          #   echo ${{secrets.PROD_PASSWORD}} | sudo -S supervisorctl reload 


      